export enum RpcErrorCode {
    INTERNAL,
    TRY_AGAIN_LATER,
    INVALID_REQUEST,
    RESOURCE_UNAVAILABLE,
    METHOD_NOT_FOUND,
    INSUFFICIENT_PERMISSIONS,
    REJECTED_BY_USER,
    CONNECTION_IS_NOT_INITIALIZED,
    MESSAGE_EXPIRED,
}
