name: nekoton_flutter
description: Flutter plugin for TON wallets core
version: 0.0.2
homepage: "https://github.com/broxus/nekoton-flutter"

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.29.2'

dependencies:
  args: ^2.7.0
  async: 2.12.0
  ffi: ^2.1.4
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  rxdart: ^0.28.0
  tuple: ^2.0.2

dev_dependencies:
  build_runner: ^2.5.4
  ffigen: ^19.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  lint: ^2.8.0

flutter:
  plugin:
    platforms:
      android:
        package: com.broxus.nekoton_flutter
        pluginClass: NekotonFlutterPlugin
      ios:
        pluginClass: NekotonFlutterPlugin

  assets:
    - assets/
    - assets/js/

ffigen:
  name: "Bindings"
  description: "Generated bindings"
  output: "lib/src/bindings.ffigen.dart"
  llvm-path:
    - "/opt/homebrew/opt/llvm"
  headers:
    entry-points:
      - "rust/gen/bindings.h"
  functions:
    symbol-address:
      include:
        - ".*_free_ptr"
