enum NativeStatus {
  success,
  mutexError,
  conversionError,
  accountsStorageError,
  keyStoreError,
  tokenWalletError,
  tonWalletError,
  genericContractError,
  cryptoError,
  dePoolError,
  abiError,
  connectionError,
  transportError,
}
